# Generated by Django 3.1.12 on 2022-01-08 22:42

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PlayLists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlists',
            name='user',
            field=djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watchlists',
            name='watchlists',
            field=djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='PlayLists.watchlist'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='movies',
            field=djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='Movies.movie'),
        ),
    ]
