# Generated by Django 3.1.12 on 2022-01-08 22:42

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('poster', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to='')),
                ('header', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to='')),
                ('release_date', models.DateField()),
                ('average_rating', models.IntegerField(default=0)),
                ('user_rating', models.IntegerField(default=0)),
                ('is_adult', models.BooleanField(default=False)),
            ],
        ),
    ]
